fix ductile protocol parameter
threatgrid/ctia pull request #1008
Opened 2020-10-02 13:42 UTC by ereteog

> Related #threatgrid/iroh/issues/4216
> Related #threatgrid/iroh/issues/3072

Ductile uses a parameter `protocol` instead of `transport` to precise the uri protocol in the ESConn.
I was not used in CTIA tests neither in any of our deployed instances that use the default value (`http`). Thus this bug did not appearwhen I introduced ductile.

<a name="qa">[§](#qa)</a> QA
============================

No QA is needed.

2020-10-05 09:04 UTC, yogsototh requested changes
You made a typo and it could break the deployed env.

2020-10-05 09:04 UTC, yogsototh commented on test/ctia/task/migration/store_test.clj
> +                          :protocol "http"
🔵  This is declared as `s/Keyword` but you use a string here.

2020-10-05 09:04 UTC, yogsototh commented on src/ctia/task/migration/store.clj
> +    :protocol s/Keyword
Sounds safer to use an enum here.

```suggestion
    :protocol (s/enum :http :https)
```

2020-10-05 09:04 UTC, yogsototh commented on resources/ctia-default.properties
> +ctia.migration.store-keys==malware,tool
🔴 

```suggestion
ctia.migration.store-keys=malware,tool
```

2020-10-05 21:13 UTC, vemv approved these changes

2020-10-06 08:23 UTC, yogsototh approved these changes
LGTM!

2020-10-06 08:26 UTC, merged