Add recently joined team members as code owners
threatgrid/ctia pull request #1137
Opened 2021-07-20 21:18 UTC by rplevy

2021-07-20 21:35 UTC, ereteog requested changes
Some parts are too sensitive, we can include sub directories when I am back.

2021-07-21 23:38 UTC, agzam approved these changes

2021-07-22 06:13 UTC, ereteog approved these changes
I am on PTO and cannot attend ongoing discussions.
Let's stick to my general rule: trust by default but don't mess with it 😉.
I would like to check ES related changes, mapping errors are VERY expensive to fix.

2021-07-22 17:51 UTC, irinarenteria approved these changes

2021-07-22 20:48 UTC, wandersoncferreira approved these changes

2021-07-23 15:55 UTC, rplevy commented
Resolution on CTIA codeowners is that the codeowners file is not actually enforced (we have never had the "require code owner approval" box checked) but @gbuisson says let's leave the file anyway as it pertains to notifying people.

2021-07-23 15:55 UTC, merged